name: lambda deploy

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "./github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"

    steps:
      - name: Chechout
        uses: actions/chechout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          # cache-dependency-path: "**/package-lock.json"

      - name: npm ci
        run: |
          npm ci

      - name: lambda build and update
        run: |
          zip -r package.zip ./*
          aws lambda update-function-code --function-name ${{secrets.LAMBDA_FUNCTION_NAME}} --zip-file fileb://package.zip --publish
